# Generated by Django 3.2.5 on 2021-07-12 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='автор')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('text_example', models.TextField(verbose_name='отрывок книги')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Discussions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='автор')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'Дискусия',
                'verbose_name_plural': 'Дискусии',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='автор')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='текст новости')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации')),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_author', models.CharField(max_length=50, verbose_name='Автор')),
                ('com_text', models.CharField(max_length=300, verbose_name='Комментарий')),
                ('com_date', models.DateTimeField(auto_now_add=True, verbose_name='дата комментария')),
                ('com_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.news')),
            ],
            options={
                'verbose_name': 'Комментарий новости',
                'verbose_name_plural': 'Коментарии новости',
            },
        ),
        migrations.CreateModel(
            name='DiscussionsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_author', models.CharField(max_length=50, verbose_name='автор')),
                ('com_text', models.CharField(max_length=300, verbose_name='комментарий')),
                ('com_date', models.DateTimeField(auto_now_add=True, verbose_name='дата комментария')),
                ('com_discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.discussions')),
            ],
            options={
                'verbose_name': 'Коментарий дискусии',
                'verbose_name_plural': 'Коментарии дискускии',
            },
        ),
        migrations.CreateModel(
            name='BookComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_author', models.CharField(max_length=50, verbose_name='Автор')),
                ('com_text', models.CharField(max_length=300, verbose_name='Комментарий')),
                ('com_date', models.DateTimeField(auto_now_add=True, verbose_name='дата комментария')),
                ('com_discuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.book')),
            ],
            options={
                'verbose_name': 'Комментарий книги',
                'verbose_name_plural': 'Коментарии книги',
            },
        ),
    ]
